# Generated by Django 4.2.14 on 2024-09-02 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenceRequest",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[
                            ("pending", "pending"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                        ],
                        default="pending",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        verbose_name="status changed",
                    ),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("licence_key", models.CharField(max_length=20, unique=True)),
                (
                    "company_name",
                    models.CharField(
                        max_length=200, verbose_name="Nom de l'entreprise"
                    ),
                ),
                (
                    "company_address",
                    models.TextField(
                        help_text="Adresse complète de l'entreprise",
                        verbose_name="Adresse de l'entreprise",
                    ),
                ),
                (
                    "company_phone",
                    models.CharField(
                        help_text="Numéro de téléphone de l'entreprise",
                        max_length=20,
                        verbose_name="Téléphone de l'entreprise",
                    ),
                ),
                (
                    "company_email",
                    models.EmailField(
                        help_text="Email de l'entreprise",
                        max_length=254,
                        verbose_name="Email de l'entreprise",
                    ),
                ),
                (
                    "company_website",
                    models.URLField(
                        blank=True,
                        help_text="Site web de l'entreprise",
                        verbose_name="Site web de l'entreprise",
                    ),
                ),
                (
                    "company_logo",
                    models.ImageField(
                        upload_to="company_logos", verbose_name="Logo de l'entreprise"
                    ),
                ),
                ("company_country", django_countries.fields.CountryField(max_length=2)),
                (
                    "company_id_number",
                    models.CharField(
                        help_text="Numéro d'identification fiscale de l'entreprise",
                        max_length=20,
                        verbose_name="Numéro d'identification fiscale",
                    ),
                ),
                (
                    "company_description",
                    models.TextField(
                        blank=True,
                        help_text="Description de l'entreprise",
                        verbose_name="Description de l'entreprise",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Message à l'attention de MPERESBONHEUR",
                        verbose_name="Message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="licence_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LicenceRequestAttachment",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        upload_to="licence_request_attachments",
                        verbose_name="Pièce jointe",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom de la pièce jointe",
                        max_length=200,
                        verbose_name="Nom",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description de l'attachement",
                        verbose_name="Description",
                    ),
                ),
                (
                    "licence_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="licences.licencerequest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Licence",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("licence_key", models.CharField(max_length=20, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'expiration"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_licences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="providers.provider",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_licences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
