# Generated by Django 4.2.14 on 2024-09-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("licences", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licencerequest",
            name="licence_key",
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
