# Generated by Django 4.2.14 on 2024-09-03 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("licences", "0002_alter_licencerequest_licence_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="licence",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="licences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
