# Generated by Django 4.2.14 on 2024-09-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("licences", "0003_licence_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licence",
            name="licence_key",
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
