# Generated by Django 4.2.7 on 2023-11-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='file',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to='products/'),
        ),
    ]
