# Generated by Django 4.2.7 on 2023-11-30 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_cover_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='file',
        ),
    ]
