# Generated by Django 4.2.7 on 2023-12-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_image_product_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='age',
            field=models.CharField(choices=[('Tout-petit', 'Tout-petit'), ('Petit', 'Petit'), ('Grand', 'Grand'), ('Tout-age', 'Tout-age')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('L', 'Livre'), ('M', 'Musique'), ('V', 'Vidéo')], max_length=10),
        ),
    ]
