# Generated by Django 4.2.7 on 2023-11-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='products/')),
                ('type', models.CharField(choices=[('L', 'Livre'), ('M', 'Musique'), ('V', 'Vidéo')], max_length=1)),
                ('age', models.CharField(choices=[('T', 'Tout-petit'), ('P', 'Petit'), ('G', 'Grand'), ('T', 'Tout-age')], max_length=1)),
                ('file', models.FileField(upload_to='products/')),
            ],
        ),
    ]
