# Generated by Django 4.2.14 on 2024-08-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Catégorie", "verbose_name_plural": "Catégories"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Produit", "verbose_name_plural": "Produits"},
        ),
        migrations.AddField(
            model_name="category",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="categories/"),
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AlterField(
            model_name="product",
            name="external_link",
            field=models.URLField(help_text="Lien de dropshipping"),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                related_name="products",
                to="marketplace.category",
                verbose_name="Catégorie",
            ),
        ),
    ]
