# Generated by Django 4.2.14 on 2024-08-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0003_product_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="external_link",
            field=models.URLField(blank=True, help_text="Lien de dropshipping"),
        ),
    ]
