# Generated by Django 4.2.14 on 2024-08-06 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0005_product_image_alter_category_name_alter_product_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="quantity",
        ),
    ]
