# Generated by Django 4.2.14 on 2024-08-17 22:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0006_remove_product_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Checkout",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("last_name", models.CharField(max_length=50, verbose_name="Nom")),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="Prénom(s)"),
                ),
                ("address", models.CharField(max_length=100, verbose_name="Adresse")),
                ("city", models.CharField(max_length=100, verbose_name="Ville")),
                (
                    "zip_code",
                    models.CharField(max_length=20, verbose_name="Code Postal"),
                ),
                ("country", models.CharField(max_length=50, verbose_name="Country")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=50, verbose_name="Adresse E-mail"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numero de téléphone"
                    ),
                ),
                ("order_notes", models.TextField(blank=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("paypal", "PayPal"),
                            ("cash", "Cash"),
                        ],
                        max_length=12,
                        verbose_name="Méthode de paiement",
                    ),
                ),
                ("card_number", models.CharField(blank=True, max_length=16)),
                ("card_expiry", models.CharField(blank=True, max_length=5)),
                ("card_cvv", models.CharField(blank=True, max_length=3)),
                (
                    "paypal_address",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Adresse PayPal"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[
                            ("pending", "pending"),
                            ("processing", "processing"),
                            ("completed", "completed"),
                        ],
                        default="pending",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        verbose_name="status changed",
                    ),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=50, verbose_name="Nom"),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=50, verbose_name="Prénoms"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Adresse E-mail"
                    ),
                ),
                (
                    "total_ht",
                    models.FloatField(editable=False, verbose_name="Total Hors-Taxe"),
                ),
                (
                    "total_ttc",
                    models.FloatField(editable=False, verbose_name="Total TTC"),
                ),
                (
                    "total_tva",
                    models.FloatField(editable=False, verbose_name="Total TVA"),
                ),
                (
                    "shipping_amount",
                    models.FloatField(
                        default=0.0, editable=False, verbose_name="Frais de livraison"
                    ),
                ),
                (
                    "checkout",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="marketplace.checkout",
                        verbose_name="Checkout",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(editable=False, max_length=100),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Quantité"),
                ),
                ("total", models.FloatField(verbose_name="Total")),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="marketplace.order",
                        verbose_name="Commande",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="marketplace.product",
                        verbose_name="Produit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
