# Generated by Django 4.2.14 on 2024-08-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0007_checkout_order_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="price",
            field=models.FloatField(default=0, verbose_name="Prix"),
            preserve_default=False,
        ),
    ]
