# Generated by Django 4.2.14 on 2024-08-19 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("marketplace", "0008_orderitem_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="refund_generated",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Redevance générée ?"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Fournisseur",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="total",
            field=models.FloatField(editable=False, verbose_name="Total"),
        ),
    ]
