# Generated by Django 4.2.14 on 2024-09-04 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0011_product_media_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="marketplace.order",
                verbose_name="Commande",
            ),
        ),
    ]
