# Generated by Django 4.1.5 on 2024-07-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0002_journalentry_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
