# Generated by Django 4.2.14 on 2024-08-19 17:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0004_remove_account_depth_remove_account_numchild_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"verbose_name": "Compte", "verbose_name_plural": "Comptes"},
        ),
        migrations.AlterModelOptions(
            name="businessdate",
            options={
                "verbose_name": "Journée comptable",
                "verbose_name_plural": "Journées comptables",
            },
        ),
        migrations.AlterModelOptions(
            name="chartofaccount",
            options={
                "verbose_name": "Plan comptable",
                "verbose_name_plural": "Plan comptables",
            },
        ),
        migrations.AlterModelOptions(
            name="journal",
            options={"verbose_name": "Journal", "verbose_name_plural": "Journaux"},
        ),
        migrations.AlterModelOptions(
            name="journalentry",
            options={
                "verbose_name": "Entrée de journal",
                "verbose_name_plural": "Entrées de journal",
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
    ]
