# Generated by Django 4.2.14 on 2024-09-04 07:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "providers",
            "0002_provider_company_address_provider_company_country_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="provider",
            name="description",
        ),
        migrations.RemoveField(
            model_name="provider",
            name="name",
        ),
    ]
