# Generated by Django 4.2.14 on 2024-09-04 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("providers", "0003_remove_provider_description_remove_provider_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="providers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
